server:
  port: 9092

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: '12345'
        platform: postgres
        url: jdbc:postgresql://localhost:5432/oauth
        username: postgres
    jpa:
      hibernate:
        ddl-auto: create-drop
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
      open-in-view: false
      generate-ddl: false
      properties:
        hibernate:
          temp.use_jdbc_metadata_defaults: false
